_wandb:
    value:
        cli_version: 0.23.0
        e:
            ubzynp6jlia6275l2zhagdsniyfnzrjg:
                args:
                    - --algorithm
                    - dpo
                codePath: train.py
                codePathLocal: train.py
                cpu_count: 20
                cpu_count_logical: 40
                cudaVersion: "13.0"
                disk:
                    /:
                        total: "1926574903296"
                        used: "1711992467456"
                email: sonicdog00@gmail.com
                executable: /home/jeehye/.conda/envs/rl/bin/python
                git:
                    commit: 47a948a79e8ba0a772c95dff84128222f102a3db
                    remote: https://github.com/jaylacho/CS672-Reinforcement-Learning-Final-Project.git
                gpu: NVIDIA TITAN RTX
                gpu_count: 8
                gpu_nvidia:
                    - architecture: Turing
                      cudaCores: 4608
                      memoryTotal: "25769803776"
                      name: NVIDIA TITAN RTX
                      uuid: GPU-9bca0b1c-4290-c9d5-154b-70f3b1ccc314
                    - architecture: Turing
                      cudaCores: 4608
                      memoryTotal: "25769803776"
                      name: NVIDIA TITAN RTX
                      uuid: GPU-3615e095-6078-24ad-76a0-102506f4d906
                    - architecture: Turing
                      cudaCores: 4608
                      memoryTotal: "25769803776"
                      name: NVIDIA TITAN RTX
                      uuid: GPU-bae10fac-4aee-26aa-659d-c1fe0238bd09
                    - architecture: Turing
                      cudaCores: 4608
                      memoryTotal: "25769803776"
                      name: NVIDIA TITAN RTX
                      uuid: GPU-051ff2a9-879b-2616-f84b-71207485e4f5
                    - architecture: Turing
                      cudaCores: 4608
                      memoryTotal: "25769803776"
                      name: NVIDIA TITAN RTX
                      uuid: GPU-90c3144c-90c0-d477-da93-8f444a34437a
                    - architecture: Turing
                      cudaCores: 4608
                      memoryTotal: "25769803776"
                      name: NVIDIA TITAN RTX
                      uuid: GPU-6d0d2d5b-d9a9-25b6-7e23-460b28cbf7f6
                    - architecture: Turing
                      cudaCores: 4608
                      memoryTotal: "25769803776"
                      name: NVIDIA TITAN RTX
                      uuid: GPU-755b6551-87bb-29ca-3b6c-eeae3514a1dd
                    - architecture: Turing
                      cudaCores: 4608
                      memoryTotal: "25769803776"
                      name: NVIDIA TITAN RTX
                      uuid: GPU-47779015-d4a9-aa86-cc3d-b16cdd1188b9
                host: mlvgpu65
                memory:
                    total: "540630761472"
                os: Linux-5.4.0-216-generic-x86_64-with-glibc2.31
                program: /home/jeehye/RL-GPT/train.py
                python: CPython 3.9.24
                root: /home/jeehye/RL-GPT
                startedAt: "2025-11-17T04:30:40.500339Z"
                writerId: ubzynp6jlia6275l2zhagdsniyfnzrjg
        m: []
        python_version: 3.9.24
        t:
            "1":
                - 1
                - 11
                - 49
                - 50
                - 53
            "2":
                - 1
                - 11
                - 49
                - 50
                - 53
            "3":
                - 13
                - 16
            "4": 3.9.24
            "5": 0.23.0
            "6": 4.57.1
            "12": 0.23.0
            "13": linux-x86_64
actor_out_dim:
    value:
        - 12
        - 3
agent_config_path:
    value: mineagent/conf.yaml
agent_model:
    value: mineagent
algorithm:
    value: dpo
clip_config_path:
    value: mineclip_official/config.yml
clip_model_path:
    value: mineclip_official/adjust.pth
clip_reward_mode:
    value: direct
cpu:
    value: 1
epochs:
    value: 1000
exp_name:
    value: dpo_harvest_milk_with_empty_bucket_and_cow
gamma:
    value: 0.99
gpu:
    value: "0"
horizon:
    value: 200
imitate_batch_size:
    value: 1000
imitate_buf_size:
    value: 500
imitate_epoch:
    value: 1
imitate_freq:
    value: 100
imitate_success_only:
    value: 0
reward_clip:
    value: 1
reward_dense:
    value: 1
reward_step:
    value: -1
reward_success:
    value: 100
save_all_data:
    value: 0
save_expert_data:
    value: 0
save_path:
    value: checkpoint
save_raw_rgb:
    value: 1
seed:
    value: 7
ss_k:
    value: 10
ss_model_path:
    value: ss_transformer/trained_on_youtube_interval_1_blocksize_10.pth
steps:
    value: 1000
target_kl:
    value: 0.5
task:
    value: harvest_milk_with_empty_bucket_and_cow
tasks_config_path:
    value: multi_env_config/harvest_milk.yaml
use_dense:
    value: 0
use_multi_task:
    value: 0
use_ss_reward:
    value: 0
